### ISSUE TITLE
Cannot setup EI using Vagrant configuration provided by WSO2.

### ISSUE THREAD

**Issue by tabishshamim10** [wso2/vagrant-ei#28]
**Description:**
Cannot setup EI using Vagrant configuration provided by WSO2.
I am following the below link: 
https://wso2.com/integration/install/vagrant/get-started/ 

I followed all the steps exactly, as given in the tutorial, but I am getting the following error when running 'vagrant up': 

`Error message: 
There was an error while executing VBoxManage, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: E_FAIL
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Querying NetCfgInstanceId failed (0x00000002)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 94 of file VBoxManageHostonly.cpp`

**Suggested Labels:**

WSO2 EI Vagrant, VirtualBox WSO2, Vagrant WSO2

**Suggested Assignees:**

**Affected Product Version:**
Virtual Box Version 5.2.18
Vagrant Version 2.12
WSO2 EI 6.3 from the below link is attempted to be installed: 
https://wso2.com/integration/install/vagrant/get-started/

**OS, DB, other environment details and versions:** 
Windows 10

**Steps to reproduce:**
Follow the steps in the link https://wso2.com/integration/install/vagrant/get-started/ verbatim, with the versions of VB and Vagrant on Windows 10. 

**Related Issues:**

**Comment by VimukthiPerera** [comment]
@tabishshamim10 This is a VirtualBox issue they introduced with VB5. Please go through the following issue in hashicorp/vagrant.
* https://github.com/hashicorp/vagrant/issues/6068

**Comment by msmshariq** [comment]
Answered by @VimukthiPerera, hence closing.
